### ISSUE TITLE
About deleting the AUR package

### ISSUE THREAD

**Issue by kiendang** [kiendang/aur-nvidia-container-runtime-hook-bin#1]
@jshap70 I saw your request to delete the AUR package for this. However we might consider just keep it there since the PKGBUILD for this still works (it downloads the official CentOS package that probabaly will always be there) and would be useful to ppl who want to install older versions of `nvidia-docker` (I know this is not recommended but it's something that ppl do) 🤔

**Comment by julie-is-late** [comment]
gotcha. personally I err on the side of just saying that things which are dead in upstream should just be removed as it just helps prevent confusion. In my opinion, if someone wants to keep older versions that's on them... kinda keeping in line with the "partial upgrades are not supported". Sure it'll probably work but its up to them to figure it out. 🙃

I do see your point though, it's your call.

**Comment by julie-is-late** [comment]
.... oops. I meant to remove the deletion request but it was approved, sorry. 

We obviously still have this repo so we can just repush it and create the package again if needed though.

**Comment by kiendang** [comment]
Hey it's ok. Now I thought about it actually you are right. We are better off deleting it. If someone else wants to use it they can submit the PKGBUILD again themselves. We don't need to maintain it.
